### ISSUE TITLE
Train Feature?

### ISSUE THREAD

**Issue by sgargbugreporter** [datameet/railways#2]
Why does the train feature  have absolute Lat/Long co-ordinates?

is it not possible to have the train as a set of stations - those stations have lat/long?

**Comment by batpad** [comment]
@sgargbugreporter - it is quite easy to generate the train as a list of stations, based on the JSON files provided - all the data exists to be able to construct this.

It will perhaps be useful to have a set of scripts that accomplishes some of this data munging, but I think that is out of the scope of this repository, which is really for just the raw data.

(I somewhat agree with you that the LineString per train is somewhat redundant since that information can be compiled with, but I think a common use-case is just drawing the train routes as LineStrings, so we have it in there. However, getting a list of all stations per train is pretty trivial using the Schedules and Stations files. Let me know if an example to do this would help.)

**Comment by geohacker** [comment]
@sgargbugreporter - certainly possible! You'd have to just lookup based on the schedules for each of the train. The way it is right now is easier for visualisation.
